# Site settings
title: Antek Drzewiecki
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tekje
github_username: antek-drzewiecki
linkedin_username: antekdrzewiecki

permalink: /blog/:categories/:year/:month/:day/:title/

collections:
  projects:
    output: true
    permalink: /projects/:categories/:year/:month/:day/:title/


defaults:
  -
    scope:
      path: "projects"
      type: "projects" # previously `page` in Jekyll 2.2.
    values:
      layout: "post" # overrides previous default layout
      author: "Antek Drzewiecki"



# pagination
paginate: 5
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
gems:
 - jekyll-coffeescript
 - jekyll-paginate